import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// components
import NavBar from "@/components/nav-bar";
//
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Portfolio",
    description: "Generated by create next app"
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body className={inter.className + " min-h-screen bg-[#070707] py-4 md:py-10 px-10 lg:px-20"}>
        <NavBar />
        {children}
        </body>
        </html>
    );
}
